### ISSUE TITLE
Alerts not getting deliverd

### ISSUE THREAD

**Issue by Glen92** [BryceCanyonCounty/bcc-job-alerts#6]
cannot get it to work, what am i doing wrong?
I see the origin text but the alerts are not getting deliverd to people who are police or medic.

**Comment by AndrewR3K** [comment]
Ill be taking a look this weekend. Last I checked it was working. But the job must be on the character already when logging in. If the player goes off/onduty it does not see that update currently.

**Comment by Glen92** [comment]
i see yeah true when you change job or go on or off duty it doesn't see the update
